
NR_ACTIVE_CONNECTIONS = 10
NUMBER_OF_PATHS = 3

NR_EPOCHS = 10
EPOCH_SIZE = 10

NOTES = ""
PATH_SIMULATION = "c:/Users/Utilizador/Ambiente de Trabalho/Tese/RRC_DRL_Update/RRC_DRL_Updates"
SIM_NR = "20250612_134604_local_critic_duelling_q_network"


INCREASE_BANDWIDTH_INTERVAL = 3
BANDWIDTH_INCREASE_FACTOR = 1.4
MAX_BANDWIDTH_MULTIPLIER = 2.0
STABILIZE_BANDWIDTH = True
STABILIZE_AFTER_MULTIPLIER = 1.75  
SAVE_REMOVED_LINKS_SCENARIO4 = True

TOPOLOGY_TYPE = "internet"; NUMBER_OF_HOSTS = 25; NUMBER_OF_AGENTS = 25; NR_MAX_LINKS = 11
STATE_SIZE = NR_MAX_LINKS + 1 + NR_ACTIVE_CONNECTIONS * 2 + 1

CRITIC_DOMAIN = "local_critic"
NEURAL_NETWORK = "duelling_q_network"

EVALUATE = True
UPDATE_WEIGHTS = False
TRAIN = False

MODIFIED_NETWORK = "remove_edges"

# Controla se a GNN � usada ou n�o
USE_GNN = False
