
NR_ACTIVE_CONNECTIONS = 10
NUMBER_OF_PATHS = 3

NR_EPOCHS = 5
EPOCH_SIZE = 5

NOTES = ""
PATH_SIMULATION = "/workspaces/MADDPGRoutingGNN"
SIM_NR = "20251006_153825_local_critic_duelling_q_network_GNN"

INCREASE_BANDWIDTH_INTERVAL = 1
BANDWIDTH_INCREASE_FACTOR = 2
MAX_BANDWIDTH_MULTIPLIER = 2
STABILIZE_BANDWIDTH = True
STABILIZE_AFTER_MULTIPLIER = 2
SAVE_REMOVED_LINKS_SCENARIO4 = True

TOPOLOGY_TYPE = "internet"; NUMBER_OF_HOSTS = 25; NUMBER_OF_AGENTS = 25; NR_MAX_LINKS = 11
STATE_SIZE = NR_MAX_LINKS + 1 + NR_ACTIVE_CONNECTIONS * 2 + 1

CRITIC_DOMAIN = "local_critic"
NEURAL_NETWORK = "duelling_q_network"

EVALUATE = False
UPDATE_WEIGHTS = False
TRAIN = False

MODIFIED_NETWORK = "remove_edges"

NUM_LINKS_TO_REMOVE = 0

# Controla se a GNN é usada ou não
USE_GNN = True
