
NR_ACTIVE_CONNECTIONS = 10
NUMBER_OF_PATHS = 3

NR_EPOCHS = 5
EPOCH_SIZE = 5

NOTES = ""
PATH_SIMULATION = "c:/Users/Utilizador/Ambiente de Trabalho/Tese/RRC_DRL_Update/RRC_DRL_Updates"
SIM_NR = "20250415_151733_central_critic_duelling_q_network"
CHECKPOINT = False
CHECKPOINT_FILE = ""

INCREASE_BANDWIDTH_INTERVAL = 3
BANDWIDTH_INCREASE_FACTOR = 1.4
MAX_BANDWIDTH_MULTIPLIER = 2.0
STABILIZE_BANDWIDTH = True
STABILIZE_AFTER_MULTIPLIER = 1.75  
SAVE_REMOVED_LINKS_SCENARIO4 = True

TOPOLOGY_TYPE = "internet"; NUMBER_OF_HOSTS = 25; NUMBER_OF_AGENTS = 25; NR_MAX_LINKS = 11
STATE_SIZE = NR_MAX_LINKS + 1 + NR_ACTIVE_CONNECTIONS * 2 + 1

CRITIC_DOMAIN = "central_critic"
NEURAL_NETWORK = "duelling_q_network"

EVALUATE = True
UPDATE_WEIGHTS = True
TRAIN = True

MODIFIED_NETWORK = "remove_edges"
